version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: kisaanmela-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-secure_password_change_me}
      MONGO_INITDB_DATABASE: kisaanmela_prod
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - kisaanmela-network
    ports:
      - "27017:27017"

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: kisaanmela-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-secure_redis_password}
    volumes:
      - redis_data:/data
    networks:
      - kisaanmela-network
    ports:
      - "6379:6379"

  # Backend API
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: kisaanmela-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://mongodb:27017/kisaanmela_prod
      - REDIS_URL=redis://redis:6379
      - PORT=5000
    env_file:
      - env.production
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    networks:
      - kisaanmela-network
    depends_on:
      - mongodb
      - redis
    ports:
      - "5000:5000"

  # Web Frontend
  web-frontend:
    build:
      context: .
      dockerfile: web-frontend/Dockerfile
    container_name: kisaanmela-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.kisaanmela.com/api
      - NEXT_PUBLIC_WEB_URL=https://kisaanmela.com
    env_file:
      - env.production
    networks:
      - kisaanmela-network
    depends_on:
      - backend
    ports:
      - "3000:3000"

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: kisaanmela-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/ssl:ro
      - ./logs/nginx:/var/log/nginx
    networks:
      - kisaanmela-network
    depends_on:
      - web-frontend
      - backend

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  kisaanmela-network:
    driver: bridge