#!/bin/bash

# 🚀 Quick Fix for Vercel MongoDB Connection Issues
# This script helps fix the 503 error on kisaanmela.com

echo "🚀 FIXING VERCEL MONGODB CONNECTION ISSUES"
echo "=========================================="
echo ""

echo "📋 Current Issue:"
echo "❌ https://www.kisaanmela.com/api/login returns 503 Service Unavailable"
echo "❌ Error: 'MongoDB not available. Use demo@kisaanmela.com/demo123...'"
echo ""

echo "🎯 SOLUTION OPTIONS:"
echo ""
echo "1. 🚀 QUICK FIX - Enable Demo Mode (Immediate)"
echo "   This will make the site work immediately with demo users"
echo ""
echo "2. 🗄️ FULL FIX - Set up MongoDB Atlas (Recommended)"
echo "   This will provide a real database for production"
echo ""
echo "3. 📋 MANUAL SETUP - Step-by-step instructions"
echo "   This will guide you through the complete setup"
echo ""

read -p "Choose option (1/2/3): " choice

case $choice in
    1)
        echo ""
        echo "🚀 QUICK FIX - ENABLE DEMO MODE"
        echo "==============================="
        echo ""
        echo "This will make your site work immediately with demo users."
        echo ""
        echo "Steps to follow:"
        echo ""
        echo "1. Go to Vercel Dashboard:"
        echo "   https://vercel.com/dashboard"
        echo ""
        echo "2. Find your kisaanmela project and click on it"
        echo ""
        echo "3. Go to Settings → Environment Variables"
        echo ""
        echo "4. Add these environment variables:"
        echo "   MONGODB_URI = demo-mode"
        echo "   DATABASE_URL = demo-mode"
        echo "   JWT_SECRET = your-super-secure-jwt-secret-key"
        echo "   NODE_ENV = production"
        echo ""
        echo "5. Click 'Save' and then 'Redeploy'"
        echo ""
        echo "6. Test the login API:"
        echo "   curl -X POST https://www.kisaanmela.com/api/login \\"
        echo "        -H 'Content-Type: application/json' \\"
        echo "        -d '{\"email\":\"demo@kisaanmela.com\",\"password\":\"demo123\"}'"
        echo ""
        echo "✅ After redeployment, these demo users will work:"
        echo "   • demo@kisaanmela.com / demo123 (farmer)"
        echo "   • admin@kisaanmela.com / admin123 (admin)"
        echo "   • buyer@kisaanmela.com / buyer123 (buyer)"
        echo "   • seller@kisaanmela.com / seller123 (seller)"
        ;;
        
    2)
        echo ""
        echo "🗄️ FULL FIX - MONGODB ATLAS SETUP"
        echo "=================================="
        echo ""
        echo "This will set up a real MongoDB database for production."
        echo ""
        echo "Steps to follow:"
        echo ""
        echo "1. Create MongoDB Atlas Account:"
        echo "   • Go to https://www.mongodb.com/atlas"
        echo "   • Sign up for free account"
        echo "   • Create project 'Kisaan Mela'"
        echo ""
        echo "2. Create Database Cluster:"
        echo "   • Choose 'Build a Database'"
        echo "   • Select 'M0 Sandbox' (Free tier)"
        echo "   • Choose your region"
        echo "   • Create cluster (takes 1-3 minutes)"
        echo ""
        echo "3. Configure Database Access:"
        echo "   • Go to 'Database Access'"
        echo "   • Add new user: kisaanmela_user"
        echo "   • Generate secure password"
        echo "   • Set privileges: 'Read and write to any database'"
        echo ""
        echo "4. Configure Network Access:"
        echo "   • Go to 'Network Access'"
        echo "   • Add IP Address: 0.0.0.0/0 (Allow from anywhere)"
        echo ""
        echo "5. Get Connection String:"
        echo "   • Go to 'Clusters'"
        echo "   • Click 'Connect' → 'Connect your application'"
        echo "   • Copy connection string"
        echo ""
        echo "6. Add to Vercel Environment Variables:"
        echo "   MONGODB_URI = mongodb+srv://kisaanmela_user:PASSWORD@cluster0.xxxxx.mongodb.net/kisaanmela_prod?retryWrites=true&w=majority"
        echo "   DATABASE_URL = mongodb+srv://kisaanmela_user:PASSWORD@cluster0.xxxxx.mongodb.net/kisaanmela_prod?retryWrites=true&w=majority"
        echo "   JWT_SECRET = your-super-secure-jwt-secret-key"
        echo "   NODE_ENV = production"
        echo ""
        echo "7. Redeploy your Vercel application"
        echo ""
        echo "✅ After setup, you'll have a real database with persistent data!"
        ;;
        
    3)
        echo ""
        echo "📋 MANUAL SETUP - STEP-BY-STEP INSTRUCTIONS"
        echo "==========================================="
        echo ""
        echo "For detailed instructions, see:"
        echo "📖 VERCEL_DEPLOYMENT_GUIDE.md"
        echo ""
        echo "This guide includes:"
        echo "• Complete MongoDB Atlas setup"
        echo "• Vercel environment variable configuration"
        echo "• Troubleshooting steps"
        echo "• Testing procedures"
        echo ""
        echo "Quick reference:"
        echo "• MongoDB Atlas: https://www.mongodb.com/atlas"
        echo "• Vercel Dashboard: https://vercel.com/dashboard"
        echo "• Test API: https://www.kisaanmela.com/api/login"
        ;;
        
    *)
        echo "❌ Invalid choice. Please run the script again and choose 1, 2, or 3."
        exit 1
        ;;
esac

echo ""
echo "🔍 TROUBLESHOOTING:"
echo "   If you still get 503 errors after setup:"
echo "   1. Check Vercel logs: Dashboard → Project → Functions → View Logs"
echo "   2. Verify environment variables are set correctly"
echo "   3. Make sure you redeployed after adding environment variables"
echo "   4. Test with demo users first: demo@kisaanmela.com / demo123"
echo ""
echo "📞 NEED HELP?"
echo "   If you encounter issues:"
echo "   1. Check the VERCEL_DEPLOYMENT_GUIDE.md for detailed instructions"
echo "   2. Verify your MongoDB Atlas connection string"
echo "   3. Make sure Vercel environment variables are set"
echo "   4. Check Vercel deployment logs for errors"
echo ""
echo "✅ Ready to fix your kisaanmela.com MongoDB connection!"
